import { TextEdit, LineEdit, Button, VerticalBox} from "std-widgets.slint";


export component AppWindow inherits Window {
property <string> results:"";
callback divide_money(string);

    background: #313e50;
GridLayout {
    padding: 25px;
    spacing: 25px;
    Row{
Text {
    text: "Enter Your Money: ";
    horizontal-alignment: center;
    font-size: 24px;
    font-weight: 900;
    color: #8d94fc;

}
    }
    Row{

  money:= LineEdit {
            font-size: 16px;
           placeholder-text: "Enter your number";
           horizontal-alignment: center;
           height: 35px;
        
        
        }
    }
    Row{
        Button {
            text: "Calculate";
            height: 35px;
            primary: true;
            clicked => {divide_money(money.text)}
        }

    }
    Row{
        VerticalBox {
            Rectangle {
                height: 100px;
                background: #f2f2f2;
                Text {
                    color: black;
                    font-size: 16px;
                    font-weight: 500;
                    text: root.results;
                }
            }
        }
    }
}  
}
